<%= form_with(model: @user, local: true) do |f| %>

  <% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger" role="alert">
      <h4><%= @user.errors.count %> 件のエラーが発生しました。</h4>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <table class="user_form">
    <tr>
      <th><%= f.label :名前 %></th>
      <td><%= f.text_field :name, size: "40" %></td>
    </tr>
    <tr>
      <th><%= f.label :メールアドレス %></th>
      <td><%= f.email_field :email, size: "40" %></td>
    </tr>
    <tr>
      <th><%= f.label :プロフィール画像（任意） %></th>
      <td><%= f.file_field :face_image %></td>
    </tr>
    <tr>
      <th><%= f.label :パスワード（6文字以上） %></th>
      <td><%= f.password_field :password, size: "40" %></td>
    </tr>
    <tr>
      <th><%= f.label :パスワードの確認 %></th>
      <td><%= f.password_field :password_confirmation, size: "40" %></td>
    </tr>
  </table>

<br>
<%= f.submit "登録" %>
<% end %>
